const ADD_MEAL = "ADD_MEAL";
const DELETE_MEAL = "DELETE_MEAL";
const CHANGE_OPTIONS_SAGA = "ADD_MEAL_SAGA";
const CHANGE_OPTIONS = "CHANGE_OPTIONS";
const ADD_TARGET_INFO = "ADD_TARGET_INFO";
const INITIAL_UPDATE = "INITIAL_UPDATE";
const USER_DATA_CHANGE = "USER_DATA_CHANGE";
const PIC_UPLOAD = "PIC_UPLOAD";

export {
  ADD_MEAL,
  DELETE_MEAL,
  CHANGE_OPTIONS_SAGA,
  CHANGE_OPTIONS,
  ADD_TARGET_INFO,
  INITIAL_UPDATE,
  USER_DATA_CHANGE,
  PIC_UPLOAD,
};
