const ADD_MEAL = "ADD_MEAL";
const DELETE_MEAL = "DELETE_MEAL";
const ADD_TARGET_INFO = "ADD_TARGET_INFO";
const INITIAL_UPDATE = "INITIAL_UPDATE";

export { ADD_MEAL, DELETE_MEAL, ADD_TARGET_INFO, INITIAL_UPDATE };
